name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -e .
          pip install -r requirements-dev.txt
          pip install flake8
      
      - name: flake8
        run: flake8 .
      
      - name: Run tests
        run: pytest
