name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install flake8

      - name: flake8
        run: flake8 . || true # preventing CI failing while flake8 issues exist
      
      - name: flake8 validating correct file(s)
        run: flake8 test/benchmark/cache_examples.py test/benchmark/code_extraction.py test/benchmark/params_examples.py test/benchmark/subdir/time_subdir.py test/benchmark/time_examples.py test/benchmark/time_secondary.py test/benchmark/timeraw_examples.py